### ISSUE TITLE
translate() always auto-detecting the source language

### ISSUE THREAD

**Issue by AndreaGallina** [vsetka/deepl-translator#6]
I noticed an unwanted behavior in the "translate()" method: it always autodetects the source language even when you specify a valid source language. To fix this I changed the `resolvedSourceLanguage` variable specified at line 63 of `deepl-translator.js` with `sourceLanguage` and now it works as expected (using the chosen source language or autodetecting it when not specified).

**Comment by vsetka** [comment]
This was intentional as I needed this for my internal use-case. The idea was to just plug in any text and it would be translated to target language correctly, even if multiple input paragraphs are in different languages. Source language should probably not be even an argument to `translate` method.

If you want more control over translation, you can use `wordAlternatives` with no beginning offset. The language is set explicitly there.

I would like to clean up the API and perhaps support the commercial API version with API keys but I don't have time to dedicate to this at the moment.
